load("//Config:configs.bzl", "app_binary_configs", "library_configs", "pretty", "info_plist_substitutions", "bundle_identifier", "DEVELOPMENT_LANGUAGE")
load("//Config:app_configuration.bzl", "appConfig", "app_name", "get_bundle_static", "get_package_name")
apple_asset_catalog(
    name = "AppAssets",
    visibility = ["//App:"],
    app_icon = "AppIcon",
    dirs = ["Assets.xcassets"],
)

# This is a list of all of our first-party libraries that are depended upon (directly or transitively) by this application.
# Every first-party library has an associated test target. We use this list to determine what test targets to run in CI.
third_party = [
    
]
submodule_dependencies = [
    "//Submodules/MainShopping:MainShopping",
    "//Submodules/AppConfiguration:AppConfiguration",
]

prebuilt_frameworks = []

# Build Phase scripts need to be added as dependencies.
# These only get executed when building with Xcode, not Buck.
build_phase_scripts = [
    ":RSwiftGenerator",
]

apple_library(
    name = "AppLibrary",
    visibility = [
        "//App:",
        "//App/...",
    ],
    configs = library_configs(),
    swift_version = "4.0",
    srcs = [
        "ViewController.swift",
        "AppDelegate.swift",
        "LocalizationHelper.swift",
    ],
    deps = [
        #"//Pods:CryptoSwift",
        #"//Pods:PromiseKit",
        "//Pods:RxSwift",
        "//Pods:ReSwift",
        #"//Pods:Moya",

        ":AppAssets",

        # Resources
        "//App/Resources:AppStringResources",
        "//App/Resources:StoryboardResources",
    ]
    + third_party
    + build_phase_scripts
    + submodule_dependencies,
)

apple_binary(
    name = "AppBinary",
    visibility = [
        "//App:",
        "//App/...",
    ],
    configs = app_binary_configs(app_name()),
    swift_version = "4.0",
    srcs = [
        "BuckSupportFiles/Dummy.swift",
    ],
    deps = [
        ":AppLibrary",
    ],
)

# Defines a Build Phase script that gets executed before the "R swift generator" step
xcode_prebuild_script(
    name = "RSwiftGenerator",
    cmd = '"${SRCROOT}/../scripts/rswift_generator.sh"',
    inputs = [],
    outputs = [],
    input_file_lists = [],
    output_file_lists = [],
)
xcode_workspace_config(
    name = "workspace",
    workspace_name = app_name(),
    src_target = get_bundle_static(),
    additional_scheme_actions = {
        "Build": {
            "PRE_SCHEME_ACTIONS": ["echo 'Started'"],
            "POST_SCHEME_ACTIONS": ["echo 'Finished'"],
        },
    },
    action_config_names = {"profile": "Profile"},
)

apple_bundle(
    name = app_name(),
    visibility = [
        "//App:",
    ],
    extension = "app",
    binary = ":AppBinary",
    product_name = app_name(),
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions(app_name()),
    deps = [
        # For "#watch", https://buckbuild.com/rule/apple_bundle.html#deps
    ]
    + prebuilt_frameworks,
)

apple_package(
    name = get_package_name(),
    bundle = get_bundle_static(),
)
